repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        name: ruff-check

      - id: ruff-format
        args: [--check]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy --config-file=pyproject.toml backend/src
        language: system
        files: \.py$
        pass_filenames: false
        stages: [pre-commit]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: uv run pytest
  #       language: system
  #       files: \.py$
  #       pass_filenames: false
  #       stages: [pre-commit]
