"""Query and response models for natural language query processing.

Defines Pydantic models for query submission, status tracking, and
AI-generated response management per FR-004, FR-005, FR-008, FR-025.

Constitutional Requirements:
- All variables have explicit type annotations
- All functions have return type annotations
- Thread-based operations only (no async/await)
- mypy --strict compliant
- pylint 10.00/10.00 compliant
"""

from datetime import datetime
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class QueryStatus(str, Enum):
    """Query processing status.

    Enum values match database CHECK constraint in data-model.md
    queries table definition.

    Values:
        PENDING: Query submitted, awaiting processing
        PROCESSING: Query currently being processed by CrewAI
        COMPLETED: Query processing completed successfully
        FAILED: Query processing failed with error
        CANCELLED: Query cancelled by user per FR-025
        TIMEOUT: Query exceeded 30-second timeout per FR-025
    """

    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"
    TIMEOUT = "timeout"


class QueryCreate(BaseModel):
    """Query submission request.

    Used for POST /queries endpoint to submit natural language questions.

    Attributes:
        query_text: Natural language question (1-5000 characters)
        dataset_ids: Optional list of specific datasets to query
                     (None = query all user's datasets)
    """

    query_text: str = Field(..., min_length=1, max_length=5000)
    dataset_ids: list[UUID] | None = None


class Query(BaseModel):
    """Complete query model with processing metadata.

    Tracks query lifecycle from submission through completion
    per data-model.md queries table schema.

    Attributes:
        id: Unique query identifier (UUID)
        query_text: Natural language question submitted
        submitted_at: Query submission timestamp
        completed_at: Query completion timestamp (None if pending)
        status: Current processing status
        generated_sql: SQL query generated by CrewAI (None if pending)
        result_count: Number of rows returned (None if pending)
        execution_time_ms: Total execution time in milliseconds
    """

    id: UUID
    query_text: str
    submitted_at: datetime
    completed_at: datetime | None = None
    status: QueryStatus
    generated_sql: str | None = None
    result_count: int | None = Field(None, ge=0)
    execution_time_ms: int | None = Field(None, ge=0)

    model_config = ConfigDict(from_attributes=True)


class QueryCancel(BaseModel):
    """Request to cancel a running query.

    Used for POST /queries/{query_id}/cancel endpoint per FR-025.

    Attributes:
        query_id: UUID of query to cancel
    """

    query_id: UUID


class QueryHistory(BaseModel):
    """Paginated query history.

    Used for GET /queries endpoint response with pagination.

    Attributes:
        queries: List of query models
        total_count: Total number of queries (all pages)
        page: Current page number (1-indexed)
        page_size: Number of items per page
    """

    queries: list[Query]
    total_count: int = Field(..., ge=0)
    page: int = Field(default=1, ge=1)
    page_size: int = Field(default=50, ge=1, le=100)


class ResponseBase(BaseModel):
    """Base response model.

    Common fields for response creation and retrieval.

    Attributes:
        query_id: UUID of associated query
    """

    query_id: UUID


class Response(ResponseBase):
    """Complete response model with AI-generated content.

    HTML-formatted answer to user's natural language question,
    generated by CrewAI Result Analyst agent per FR-008.

    Attributes:
        id: Unique response identifier (UUID)
        query_id: Associated query UUID (inherited)
        html_content: Semantic HTML5 formatted answer
        plain_text: Plain text version of answer
        confidence_score: AI confidence in answer (0.0-1.0, None if unavailable)
        generated_at: Response generation timestamp
        data_snapshot: JSON snapshot of top N result rows
    """

    id: UUID
    html_content: str = Field(..., min_length=1)
    plain_text: str = Field(..., min_length=1)
    confidence_score: float | None = Field(None, ge=0.0, le=1.0)
    generated_at: datetime
    data_snapshot: dict[str, Any] | None = None

    model_config = ConfigDict(from_attributes=True)


class QueryWithResponse(Query):
    """Query with embedded response.

    Composite model combining query and response for
    GET /queries/{query_id} endpoint per openapi.yaml.

    Attributes:
        response: Associated response model (None if query not completed)
    """

    response: Response | None = None
